const GITHUB_PR_APPROVED_STATE = "APPROVED";
const GITHUB_PR_COMMENTED_STATE = "COMMENTED";
const GITHUB_PR_CHANGES_REQUESTED_STATE = "CHANGES_REQUESTED";

const UAT_APPROVED_STATE = "UAT_APPROVED";
const UAT_NOT_REQUIRED_STATE = "UAT_NOT_REQUIRED";
const UAT_CHANGES_REQUESTED_STATE = "UAT_CHANGES_REQUESTED";

const DEFAULT_TEAM_REVIEWER_COUNT = 2;
const DEFAULT_KEY_REVIEWER_COUNT = 1;
const DEFAULT_UAT_SLOT = true;

const ICON_BLANK_SQUARE = "⬜";
const ICON_BLANK_CIRCLE = "⚪";
const ICON_APPROVED = "✅";
const ICON_CHANGES = "❗";
const ICON_COMMENT = "💬";
const ICON_KEY_REVIEWER_APPROVED = "✨";
const ICON_KEY_REVIEWER_CHANGES = "❕";
const ICON_KEY_REVIEWER_COMMENT = "🗨️";
const ICON_UAT_APPROVED = "🎨";
const ICON_UAT_NOT_REQUIRED = "⚪";
const ICON_UAT_CHANGES = "🖌️";
const ICON_WARNING = "⚠️";
const ICON_TIME_SENSITIVE = "⏲️";

module.exports = {
  GITHUB_PR_APPROVED_STATE,
  GITHUB_PR_COMMENTED_STATE,
  GITHUB_PR_CHANGES_REQUESTED_STATE,
  UAT_APPROVED_STATE,
  UAT_NOT_REQUIRED_STATE,
  UAT_CHANGES_REQUESTED_STATE,
  DEFAULT_TEAM_REVIEWER_COUNT,
  DEFAULT_KEY_REVIEWER_COUNT,
  DEFAULT_UAT_SLOT,
  ICON_BLANK_SQUARE,
  ICON_BLANK_CIRCLE,
  ICON_APPROVED,
  ICON_CHANGES,
  ICON_COMMENT,
  ICON_KEY_REVIEWER_APPROVED,
  ICON_KEY_REVIEWER_CHANGES,
  ICON_KEY_REVIEWER_COMMENT,
  ICON_UAT_APPROVED,
  ICON_UAT_NOT_REQUIRED,
  ICON_UAT_CHANGES,
  ICON_WARNING,
  ICON_TIME_SENSITIVE
};
